# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:03
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=redactor.fields.RedactorField(default='summary', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
